/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LewisBan9003LewisBan9003LewisBan9003LewisBan9003RouteImport } from './routes/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChatHistoryRouteImport } from './routes/chat-history'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SupportRouteImport } from './routes/support'
import { Route as OrdersCodeRouteImport } from './routes/orders.$code'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route =
  LewisBan9003LewisBan9003LewisBan9003LewisBan9003RouteImport.update({
    id: '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003',
    path: '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003',
    getParentRoute: () => rootRouteImport,
  } as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatHistoryRoute = ChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCodeRoute = OrdersCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003': typeof LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route
  '/cart': typeof CartRoute
  '/chat-history': typeof ChatHistoryRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/support': typeof SupportRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003': typeof LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route
  '/cart': typeof CartRoute
  '/chat-history': typeof ChatHistoryRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/support': typeof SupportRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003': typeof LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route
  '/cart': typeof CartRoute
  '/chat-history': typeof ChatHistoryRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/support': typeof SupportRoute
  '/orders/$code': typeof OrdersCodeRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
    | '/cart'
    | '/chat-history'
    | '/checkout'
    | '/orders'
    | '/policies'
    | '/privacy-policy'
    | '/products'
    | '/support'
    | '/orders/$code'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
    | '/cart'
    | '/chat-history'
    | '/checkout'
    | '/orders'
    | '/policies'
    | '/privacy-policy'
    | '/products'
    | '/support'
    | '/orders/$code'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
    | '/cart'
    | '/chat-history'
    | '/checkout'
    | '/orders'
    | '/policies'
    | '/privacy-policy'
    | '/products'
    | '/support'
    | '/orders/$code'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route: typeof LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route
  CartRoute: typeof CartRoute
  ChatHistoryRoute: typeof ChatHistoryRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  SupportRoute: typeof SupportRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003': {
      id: '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
      path: '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
      fullPath: '/Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003-Lewis-Ban-9003'
      preLoaderRoute: typeof LewisBan9003LewisBan9003LewisBan9003LewisBan9003RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-history': {
      id: '/chat-history'
      path: '/chat-history'
      fullPath: '/chat-history'
      preLoaderRoute: typeof ChatHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$code': {
      id: '/orders/$code'
      path: '/$code'
      fullPath: '/orders/$code'
      preLoaderRoute: typeof OrdersCodeRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersCodeRoute: typeof OrdersCodeRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersCodeRoute: OrdersCodeRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route:
    LewisBan9003LewisBan9003LewisBan9003LewisBan9003Route,
  CartRoute: CartRoute,
  ChatHistoryRoute: ChatHistoryRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  SupportRoute: SupportRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
